name: PR CI

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: gd, yaml, mysqli, pdo_mysql
          tools: composer

      - name: Install Composer dependencies
        run: composer install --no-progress --no-interaction --prefer-dist

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit --colors=always

      - name: Run PHPStan analysis
        run: ./vendor/bin/phpstan analyse src --level=max
